### ISSUE TITLE
PyArff 0.1 Release roadmap

### ISSUE THREAD

**Issue by raghavrv** [pyarff/pyarff#1]
TODO
- [ ] Setup travis.
- [ ] Setup circleci
- [ ] Make sparse work
- [ ] Simplify metadata dict
- [ ] `@attribute name{}` does not parse correctly debug.
- [ ] For the soybean dataset, the last entry is not parsed correctly.
- [ ] Parse `@inputs` `@outputs`
- [ ] Use `np.recarray`
- [ ] Parse `STRING` attribute
- [ ] Parse `DATE` attribute (as string)
- [ ] Support pandas output

**Comment by mfeurer** [comment]
[liac-arff](https://github.com/renatopp/liac-arff) contains a pretty broad set of unit tests for arff data. It should be included as a bullet point to your list to import those tests as well. Also, some form of documentation would be a good todo object.
